[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "nano-sglang"
version = "0.0.1"
description = "nano SGLang: LLM inference framework"
readme = "README.md"
requires-python = ">=3.9"
license = { file = "LICENSE" }
classifiers = ["Programming Language :: Python :: 3"]
dependencies = ["requests"]

[project.optional-dependencies]
all = [
    "fastapi",
    "psutil",
    "rpyc",
    "torch>=2.8.0",
    "transformers>=4.33,<5",
    "triton; platform_system == 'Linux' and platform_machine == 'x86_64'",
    "uvloop",
    "uvicorn",
    "zmq",
    "interegular",
    "lark",
    "numba",
    "tqdm",
    "numpy",
    "requests",
    "huggingface_hub<1.0",
    "safetensors",
    "Pillow",
    "filelock",
]

[project.urls]
"Homepage" = "https://github.com/gogongxt/nano-sglang"
"Bug Tracker" = "https://github.com/gogongxt/nano-sglang/issues"
